services:
  server:
    build:
      context: .
      dockerfile: cmd/server/Dockerfile
    volumes:
      - ./runtime:/root/runtime
    ports:
      - "52333:52333"
    dns:
      - 8.8.8.8
      - 1.1.1.1
